dist: xenial
language: php

stages:
  - test

php:
  - 7.2
  - 7.3
  - master

env:
  matrix:
    - dependencies=lowest
    - dependencies=highest
matrix:
  allow_failures:
    - php: master

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libmpdec-dev
  - pecl install decimal-1.3.0

before_script:
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --no-interaction --ignore-platform-reqs; fi
  - if [ "$dependencies" = "highest" ]; then composer update --no-interaction --ignore-platform-reqs; fi

cache:
  directories:
    - $HOME/.composer/cache
